

[pytest]
addopts = -n auto --headed --browser chromium --screenshot only-on-failure --html=report.html --self-contained-html
markers =
    happy_path: marks tests as happy path
    positive: marks positive test cases
    negative: marks negative test cases
